// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHQBqrLg36vLTjvRFmZvFFg_-F8fjchE',
    appId: '1:930350527592:web:92944b5c9e10a56cb177dd',
    messagingSenderId: '930350527592',
    projectId: 'study-sphere-327cb',
    authDomain: 'study-sphere-327cb.firebaseapp.com',
    storageBucket: 'study-sphere-327cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwKZr1E8qYhi98ViIF_cqxPR9xAb7uFM',
    appId: '1:930350527592:android:89290e8d7028c7ebb177dd',
    messagingSenderId: '930350527592',
    projectId: 'study-sphere-327cb',
    storageBucket: 'study-sphere-327cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhU9MK2FOvhAZSQerJu2E_oVNzTBo4dJc',
    appId: '1:930350527592:ios:a309e4d45c0c1d40b177dd',
    messagingSenderId: '930350527592',
    projectId: 'study-sphere-327cb',
    storageBucket: 'study-sphere-327cb.firebasestorage.app',
    iosBundleId: 'com.example.studysphere',
  );
}
